spring.application.name=oneGasMeter

# Mantiene la JVM attiva senza web server
spring.main.keep-alive=true

# === Server TCP ===
tcp.server.port=60103
tcp.server.max-connections=10000
tcp.server.backlog=1000
tcp.server.session-timeout-ms=30000

# === Sessione DLMS ===
dlms.client-address=16
dlms.server-address=1
dlms.authentication=NONE
dlms.password=
dlms.use-logical-name-referencing=true

# === SQL Server DataSource ===
spring.datasource.url=jdbc:sqlserver://localhost;databaseName=OneGasDbDLMS;encrypt=true;trustServerCertificate=true
spring.datasource.username=oneGasDbDLMS_username
spring.datasource.password=oneGasDbDLMS_password
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# === JPA/Hibernate ===
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# === Logging ===
logging.level.com.aton.proj.oneGasMeter=INFO
logging.level.org.hibernate.SQL=WARN
